### ISSUE TITLE
Change order of month and year

### ISSUE THREAD

**Issue by reneeorser** [clintonhealthaccess/chailmis-android#117]
Medium Severity

Facility Stock reports should have "month" before the "year" not vice versa. also the buttons for selecting month are very small and difficult to select a specific month, make these bigger

Egwuma - Reports - 3/4/2015

**Comment by chai-lmis** [comment]
The buttons for selecting the months are now bigger and easier to select, however we still need to change the order of the date to month before the year

**Comment by cvaldez519** [comment]
TESTED. PASS. All report dropdown are now Month - Year. Also, they all continue to work probably with dates.
