### ISSUE TITLE
Reduce SOH sync delay

### ISSUE THREAD

**Issue by reneeorser** [clintonhealthaccess/chailmis-android#121]
High Severity

After an allocation is received on the tablet and synced with the server, there is a very long delay before the SOH is updated on the tablet. Is the SOH syncing from server after a receipt or is this locally caluculated on the tablet?

Egwuma - Received - 3/9/2015

**Comment by chai-lmis** [comment]
After an allocation is done successfully, the stock on hand for the allocated commodities should increase and this should be displayed on the home page graph, the sync is sometimes slow and doesnt show up  for 5 mins sometimes

**Comment by cvaldez519** [comment]
TESTED. PASS. The graph was updated and the SOH for the items are updated locally.
