### ISSUE TITLE
Sync "projected quantity to order"

### ISSUE THREAD

**Issue by reneeorser** [clintonhealthaccess/chailmis-android#122]
Critical Severity

PROJECTED QUANTITY TO ORDER doesnt sync from the server and when ordering this value shows zero even when the server has a value

Egwuma - Ordering - 3/9/2015

**Comment by chai-lmis** [comment]
This will be fixed when #136 is fixed

**Comment by chai-lmis** [comment]
Also noticed that the projected order quantity on the app is 15 for all commodities

**Comment by chai-lmis** [comment]
This is tied to card # 136

**Comment by jobasiimwe** [comment]
Projected Order Quantity is no longer necessary on the client end.
All order projections are calculated using Time of order, Type of order, Maximum stock level and Stock on Hand

**Comment by chai-lmis** [comment]
projections are calculating correctly based on the type of order, max stock level, stock on hand and date (before r after the 15th)
