### ISSUE TITLE
Distribute the application through an app-store

### ISSUE THREAD

**Issue by gigix** [clintonhealthaccess/chailmis-android#161]
In order to enable auto-updating of the mobile application, we need host it on a private app store (F-Droid). 

Here's how to setup an F-Droid app store: https://github.com/chailmis/chailmis-android/tree/master/appstore

Need CHAI to provide a server and a domain name to host the app store.

**Comment by gigix** [comment]
We can use the CI server to host F-Droid:

ssh twer@104.131.225.22
r0ys1ngh4m

Still need a domain name pointing to it.

**Comment by gigix** [comment]
Done. 

There are two repositories can be access at http://104.131.225.22/fdroid/development/ and http://104.131.225.22/fdroid/production/, stored in /var/www/html/fdroid/development and /var/www/html/fdroid/production respectively. 

To publish a development package
------

cd /var/www/html/fdroid/development/
wget http://104.131.225.22:8080/job/generate-apk/lastSuccessfulBuild/artifact/app/build/outputs/apk/app-development-debug.apk -O repo/LMIS.apk
fdroid update --create-metadata --clean --verbose

To publish a production package
-------

cd /var/www/html/fdroid/production/
wget http://104.131.225.22:8080/job/generate-apk/lastSuccessfulBuild/artifact/app/build/outputs/apk/app-production-debug.apk -O repo/LMIS.apk
fdroid update --create-metadata --clean --verbose

**Comment by karlwbrown** [comment]
Jeff, could you please add these instructions to the documentation in the git repo.

**Comment by cameotisha** [comment]
- We need to add clear steps of setting up an fdroid repository in the user guide + this card.

**Comment by cameotisha** [comment]
Test Results:
Given that fdroid has been installed on the tablet and has been opened
1. Under Available apps, DHIS2 LMIS ver 1.1 is available for installation

**Comment by karlwbrown** [comment]
Note: we should update the instructions above to reference the new URL for the private app store: lmisapp.dhis2nigeria.org.ng

**Comment by karlwbrown** [comment]
Note: I updated the instructions [here](https://github.com/chailmis/chailmis-android/blob/master/appstore/README.md) with some of the instructions from above. Jeff, could you please confirm these instructions are correct - I also updated to reference the private app store URL.

**Comment by cameotisha** [comment]
Tests
------
- Once the version number and version code are changed, the updates appear under the updates tab in fdroid and i was able to run the update
- Test Result: Passed

Limitations
-----
- you have to manually refresh the fdroid app to see the updates
- you have to manually select the DHIS LMIS app and click to install the updates, i am not sure whether this is the best way to do this.

**Comment by jobasiimwe** [comment]
I met a problem while trying to update to a new version:

The new version is signed with a different key to the old one. To install the new version, the old one must be uninstalled first. Please do this and try again. (Note that uninstalling will erase any internal data stored by the application.)

I am not sure whether i had installed the APK on the tablet without using F-Droid. (That would certainly cause this error) Incase another person encounters this, it will be an issue to resolve
