### ISSUE TITLE
Negative Stock should never arise

### ISSUE THREAD

**Issue by jobasiimwe** [clintonhealthaccess/chailmis-android#168]
Investigate scenarios where stock goes below zero and find ways to prevent them.

**Comment by karlwbrown** [comment]
This can only happen if two people using 2 different tablets both reduce stock and synch.

**Comment by karlwbrown** [comment]
Egwuma,  please confirm whether you are able to create negative stock in any situation other than the situation noted above (e.g. two people at same facility both reducing stock levels). Moving to QA.

**Comment by chai-lmis** [comment]
negative stock can also arise if data is pushed directly into the server not via the app.
