### ISSUE TITLE
test to confirm memory leak doesn't occur

### ISSUE THREAD

**Issue by karlwbrown** [clintonhealthaccess/chailmis-android#192]
You can reproduce this issue by loading report “Monthly Facility Consumption Report RH2” for many times. If you load it ~20-30 times, the app should crash. Although, now that this is fixed, it should not crash anymore.

(I had to recreate this issue as a dupe of 189, as I couldn't move card 189)

**Comment by chai-lmis** [comment]
PASSED: App does not crash anymore, tried several activities to test this
