### ISSUE TITLE
on the FP RH2 Report, Quantity Dispensed is 0, and Total quantity dispensed has figures.

### ISSUE THREAD

**Issue by chai-lmis** [clintonhealthaccess/chailmis-android#198]
The total quantity dispensed should be an aggregated value of the quantity adjusted (with the option sent to other facilities) and the quantity via the dispense activity

**Comment by cvaldez519** [comment]
TESTED. PASS. Even though the quantity dispensed is 0 because the quantity adjusted for being sent to another facility the total quantity dispensed has the correct values.
