### ISSUE TITLE
Losses for the monthly vaccines utilization report has not been added

### ISSUE THREAD

**Issue by chai-lmis** [clintonhealthaccess/chailmis-android#199]
There should be a loss section on the 2 Vaccine reports, the template for this was shared with Job

**Comment by cvaldez519** [comment]
FAILED. 

TEST

Enter losses for Vaccine - Yellow Fever Dilutent
Go to Report - Vaccine - Monthly Health Facility Vaccines Utilization Report
Select current month and year then load report. 

The results do not display losses for any of the vaccines listed, in particular none of the data captured for Yellow Fever Dilutent are displayed.

**Comment by cvaldez519** [comment]
My previous comment was incorrect. The UI is just different than the other reports, and I had to scroll with each item in order to see the data for each.
