### ISSUE TITLE
App is syncing data that has been completely deleted from the server

### ISSUE THREAD

**Issue by chai-lmis** [clintonhealthaccess/chailmis-android#215]
All Allocation data values for all facilities and commodities from 1st Jan 2015 to 25th May 2015 has been deleted, however on registration of a facility, the app syncs allocation data for 19th May 2015

**Comment by karlwbrown** [comment]
Egwuma can you confirm this still occurs - and that this wasn't an issue with the server caching data?

**Comment by chai-lmis** [comment]
TESTED: Version 1.7.507 fixes this issue
