### ISSUE TITLE
Sync on shut down

### ISSUE THREAD

**Issue by LakshmiCHAI** [clintonhealthaccess/chailmis-android#260]
Initiate a sync when the device is being shut down

**Comment by garymabin** [comment]
Syncing is a time-consuming job, even we can known the time the device is
about to shut down, we can not ensure the sync is finished. Actually the
power-off process will kill all the process that is running.

Bin MaConsultantEmailbinma@thoughtworks.comTelephone+86 13125033274
<+86+13125033274>[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=bin-ma-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

2015-10-09 3:27 GMT+08:00 LakshmiCHAI <notifications@github.com>:

**Comment by chai-lmis** [comment]
I don't think this is a good idea, as the sync may be interrupted if the shutdown is forced and this may cause the app to crash. I already noticed that when the sync on demand was unsuccessful it caused the app to crash.
Egwuma

**Comment by chai-lmis** [comment]
i believe we can close this card as its not a viable option?

**Comment by ihassin** [comment]
Please do

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=ti&cv=7.4.8&pv=9.0.2&source=email_footer_2]
On Fri, Oct 9, 2015 at 04:27, clintonhealthaccess/chailmis-android
<reply@reply.github.com>
wrote:
i believe we can close this card as its not a viable option?

—
Reply to this email directly or view it on GitHub
[https://github.com/clintonhealthaccess/chailmis-android/issues/260#issuecomment-146795731] .[https://github.com/notifications/beacon/AABKPgzuYaKWvvmLsQ5ZBKDWNC0wS1_nks5o53HcgaJpZM4GLm4A.gif]

**Comment by karlwbrown** [comment]
Closed per Bin Ma, since we can't ensure this completes before the device shuts down.
